"""Add cancellation fields and name constraints

Revision ID: 40df6cf12e98
Revises: 567d9257b3b6
Create Date: 2026-07-31 11:16:13.180205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40df6cf12e98'
down_revision = '567d9257b3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_requests_cancelled_by_users', 'users', ['cancelled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_requests_cancelled_by_users', type_='foreignkey')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by')

    # ### end Alembic commands ###
